name: Create DataProcessor release

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'PluginBrowser/**'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::v$(date +'%Y-%m-%d-%H-%M-%S')"
      
    - name: Publish DataProcessor
      run: dotnet publish DataProcessor/DataProcessor.csproj -c Release -o release -p:PublishSingleFile=true --self-contained -r linux-x64 --nologo
    - name: Release
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      with:
        tag_name: ${{ steps.date.outputs.date }}
        name: DataProcessor ${{ steps.date.outputs.date }}
        files: release/DataProcessor
        fail_on_unmatched_files: true
